--- #YAML:1.0
name:               Net-HTTPS-Any
version:            0.10
abstract:           Simple HTTPS class using whichever underlying SSL module is available
author:
    - Ivan Kohler <ivan-net-https-any@freeside.biz>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:   0
    Tie::IxHash:  0
    URI::Escape:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
