---
abstract: 'Simple HTTPS client using whichever underlying SSL module is available'
author:
  - 'Ivan Kohler <ivan-net-https-any@freeside.biz>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-HTTPS-Any
no_index:
  directory:
    - t
    - inc
requires:
  Net::SSLeay: 0
  Test::More: 0
  Tie::IxHash: 0
  URI::Escape: 0
version: 0.11
